Cast enum class objects to int in SiStripRawToDigiUnpacker `fmt::format`
When building the EventFilter packages on Arch Linux, I get this
compilation error:

```
EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc:163:36:   required from here
/usr/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1757 |       formattable
```

It happens because some enum class objects are passed to `fmt::format`,
and it doesn't know how to format them, at least in the environment I
have.

This can be solved by explicitely casting to `int`. I also replaced some
`auto` usage with the actual type, so it is easier to understand why the
changes made in this PR are necessary.