Remove initialization from VLAs
Looks like Clang does not support initialization for variable-size
objects:

    error: variable-sized object may not be initialized

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>