Add missing dep for GEMGeometry, RPCGeometry, CSCGeometry, and DTGeometry
Resolves linking errors:

    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0xdd8): undefined reference to peinfo for GEMGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0xfd8): undefined reference to peinfo for RPCGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x11d8): undefined reference to peinfo for CSCGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x13d8): undefined reference to peinfo for DTGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x2c98): undefined reference to peinfo for GEMGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x2e98): undefined reference to peinfo for GEMGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3098): undefined reference to peinfo for RPCGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3298): undefined reference to peinfo for RPCGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3498): undefined reference to peinfo for DTGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3698): undefined reference to peinfo for DTGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3898): undefined reference to peinfo for CSCGeometry'
    testGlobalTrackingGeometry/GlobalTrackingGeometryTest.o:(.data.rel+0x3a98): undefined reference to peinfo for CSCGeometry'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>