Add missing dependency for GeometricSearchDet
Resolves linking error:

    RecoMuonMeasurementDet/MuonDetLayerMeasurements.o:(.data.rel+0x3958): undefined reference to peinfo for GeometricSearchDet'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>