Add missing dependency for reco::Candidate
Resolve linking errors:

    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x18): undefined reference to peinfo for reco::Candidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x58): undefined reference to peinfo for reco::Candidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x98): undefined reference to peinfo for reco::Candidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0xd8): undefined reference to peinfo for reco::Candidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x118): undefined reference to peinfo for reco::Candidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x158): more undefined references to peinfo for reco::Candidate' follow
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x8d8): undefined reference to peinfo for reco::LeafCandidate'
    TopQuarkAnalysisTopSkimming/TtDecayChannelSelector.o:(.data.rel+0x918): undefined reference to peinfo for reco::LeafCandidate'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>