Add missing dependecy for reco::{LeafCandidate,Candidate,GenParticle}
Resolves linking errors:

    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4398): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4418): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4458): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x44d8): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4518): undefined reference to peinfo for reco::GenParticle'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4558): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4598): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4618): undefined reference to peinfo for reco::GenParticle'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4658): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4698): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x46d8): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4718): undefined reference to peinfo for reco::Candidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4858): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4a18): undefined reference to peinfo for reco::GenParticle'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4a58): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4b58): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x4b98): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x6418): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x6458): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x6498): undefined reference to peinfo for reco::GenParticle'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x6598): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x65d8): undefined reference to peinfo for reco::LeafCandidate'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel+0x6618): undefined reference to peinfo for reco::GenParticle'
    TauSpinnerInterface/TauSpinner/TauSpinnerCMS.o:(.data.rel.ro._ZTIN4reco22CompositeRefCandidateTIN3edm9RefVectorISt6vectorINS_11GenParticleESaIS4_EES4_NS1_9refhelper16FindUsingAdvanceIS6_S4_EEEEEE[_ZTIN4reco22CompositeRefCandidateTIN3edm9RefVectorISt6vectorINS_11GenParticleESaIS4_EES4_NS1_9refhelper16FindUsingAdvanceIS6_S4_EEEEEE]+0x10): undefined reference to peinfo for reco::LeafCandidate'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>