Add missing dependency for edm::TRandomAdaptor'
Resolves linking errors:

    FastSimulationUtilities/RandomEngineAndDistribution.o:(.data.rel+0x98): undefined reference to peinfo for edm::TRandomAdaptor'
    FastSimulationUtilities/RandomEngineAndDistribution.o:(.data.rel+0xd8): undefined reference to peinfo for edm::TRandomAdaptor'
    FastSimulationUtilities/RandomEngineAndDistribution.o:(.data.rel+0x458): undefined reference to peinfo for edm::TRandomAdaptor'
    FastSimulationUtilities/RandomEngineAndDistribution.o:(.data.rel+0x498): undefined reference to peinfo for edm::TRandomAdaptor'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>