Fix compilation errors introduced by automatic CMSSW code-checks.
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1446:95: warning: missing terminating " character
     if( ALIUtils::debug >= 5 ) ALIUtils::dumprm(theRmGlobOriginalOriginal, name() + ALIstring(" theRmGlobOriginalOriginal before displaced
                                                                                               ^
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1446:95: error: missing terminating " character
     if( ALIUtils::debug >= 5 ) ALIUtils::dumprm(theRmGlobOriginalOriginal, name() + ALIstring(" theRmGlobOriginalOriginal before displaced
                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1447:7: warning: missing terminating " character
       ") );
       ^
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1447:7: error: missing terminating " character
       ") );
       ^~~~~

${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc: In member function 'void OpticalObject::displaceRmGlobOriginalOriginal(const OpticalObject*, XYZcoor, ALIdouble)':
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1446:94: error: expected primary-expression before '(' token
     if( ALIUtils::debug >= 5 ) ALIUtils::dumprm(theRmGlobOriginalOriginal, name() + ALIstring(" theRmGlobOriginalOriginal before displaced
                                                                                              ^
${CMSSW_BASE}/src/Alignment/CocoaModel/src/OpticalObject.cc:1448:5: error: expected primary-expression before 'switch'
     switch( coor ) {
     ^~~~~~